Feature/1 add files
isovera/enlabeler pull request #2
Opened 2018-11-29 21:49 UTC by hhedden-isovera

2018-11-29 22:52 UTC, amanire commented on README.md
> +- Install [jq](https://stedolan.github.io/jq/) with the command `brew install jq`.
```suggestion
- Install [jq](https://stedolan.github.io/jq/) (on MacOS with [Homebrew](https://brew.sh/), use the command `brew install jq`).
```

2018-11-29 22:56 UTC, amanire commented on README.md
> +1. GitHub issue labels are assumed to use Code > Feature QA > Code Review convention as documented in
@hhedden-isovera is this line relevant without the ZenHub work? I don't think it is.

2018-11-29 22:58 UTC, amanire commented on enlabeler.sh
> +	#Grab the pipeline IDs
This work looks like it can also be removed.

2018-11-29 22:58 UTC, amanire requested changes
a little more cleanup before merging

2018-11-29 23:02 UTC, hhedden-isovera commented on README.md
> +1. GitHub issue labels are assumed to use Code > Feature QA > Code Review convention as documented in
I'm pretty sure it's no longer relevant.

2018-11-30 20:02 UTC, amanire approved these changes

2018-11-30 20:18 UTC, merged